export const INVALID_REQUEST_PARAMETERS = 'INVALID_REQUEST_PARAMETERS';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
export const UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS';
export const USER_EXISTS = 'USER_EXISTS';
export const SELF_ACCOUNT_DELETE = 'SELF_ACCOUNT_DELETE';