export const adminPermissions = [
  "add_user",
  "list_user",
  "show_user",
  "update_user",
  "delete_user",
  "add_group",
  "list_group",
  "show_group",
  "update_group",
  "delete_group",
  "add_task",
  "list_task",
  "show_task",
  "update_task",
  "delete_task",
  "show_organization",
  "update_organization"
];